// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/fctreddit/impl/api/grpc/ImageAdmin.proto

package fctreddit.impl.grpc.generated_java;

public final class ImageAdminProtoBuf {
  private ImageAdminProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AdminDeleteImageArgsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AdminDeleteImageArgs)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string userId = 1;</code>
     * @return The userId.
     */
    java.lang.String getUserId();
    /**
     * <code>string userId = 1;</code>
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>string imageId = 2;</code>
     * @return The imageId.
     */
    java.lang.String getImageId();
    /**
     * <code>string imageId = 2;</code>
     * @return The bytes for imageId.
     */
    com.google.protobuf.ByteString
        getImageIdBytes();

    /**
     * <code>string token = 3;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <code>string token = 3;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code AdminDeleteImageArgs}
   */
  public static final class AdminDeleteImageArgs extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AdminDeleteImageArgs)
      AdminDeleteImageArgsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AdminDeleteImageArgs.newBuilder() to construct.
    private AdminDeleteImageArgs(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AdminDeleteImageArgs() {
      userId_ = "";
      imageId_ = "";
      token_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AdminDeleteImageArgs();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AdminDeleteImageArgs(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              imageId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.internal_static_AdminDeleteImageArgs_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.internal_static_AdminDeleteImageArgs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs.class, fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object userId_;
    /**
     * <code>string userId = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string userId = 1;</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGEID_FIELD_NUMBER = 2;
    private volatile java.lang.Object imageId_;
    /**
     * <code>string imageId = 2;</code>
     * @return The imageId.
     */
    @java.lang.Override
    public java.lang.String getImageId() {
      java.lang.Object ref = imageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imageId_ = s;
        return s;
      }
    }
    /**
     * <code>string imageId = 2;</code>
     * @return The bytes for imageId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getImageIdBytes() {
      java.lang.Object ref = imageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 3;
    private volatile java.lang.Object token_;
    /**
     * <code>string token = 3;</code>
     * @return The token.
     */
    @java.lang.Override
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 3;</code>
     * @return The bytes for token.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(imageId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, imageId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, token_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(imageId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, imageId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, token_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs)) {
        return super.equals(obj);
      }
      fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs other = (fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs) obj;

      if (!getUserId()
          .equals(other.getUserId())) return false;
      if (!getImageId()
          .equals(other.getImageId())) return false;
      if (!getToken()
          .equals(other.getToken())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + IMAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getImageId().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AdminDeleteImageArgs}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AdminDeleteImageArgs)
        fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.internal_static_AdminDeleteImageArgs_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.internal_static_AdminDeleteImageArgs_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs.class, fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs.Builder.class);
      }

      // Construct using fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = "";

        imageId_ = "";

        token_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.internal_static_AdminDeleteImageArgs_descriptor;
      }

      @java.lang.Override
      public fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs getDefaultInstanceForType() {
        return fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs.getDefaultInstance();
      }

      @java.lang.Override
      public fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs build() {
        fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs buildPartial() {
        fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs result = new fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs(this);
        result.userId_ = userId_;
        result.imageId_ = imageId_;
        result.token_ = token_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs) {
          return mergeFrom((fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs other) {
        if (other == fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getImageId().isEmpty()) {
          imageId_ = other.imageId_;
          onChanged();
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>string userId = 1;</code>
       * @return The userId.
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userId = 1;</code>
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userId = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 1;</code>
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object imageId_ = "";
      /**
       * <code>string imageId = 2;</code>
       * @return The imageId.
       */
      public java.lang.String getImageId() {
        java.lang.Object ref = imageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          imageId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string imageId = 2;</code>
       * @return The bytes for imageId.
       */
      public com.google.protobuf.ByteString
          getImageIdBytes() {
        java.lang.Object ref = imageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string imageId = 2;</code>
       * @param value The imageId to set.
       * @return This builder for chaining.
       */
      public Builder setImageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string imageId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearImageId() {
        
        imageId_ = getDefaultInstance().getImageId();
        onChanged();
        return this;
      }
      /**
       * <code>string imageId = 2;</code>
       * @param value The bytes for imageId to set.
       * @return This builder for chaining.
       */
      public Builder setImageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imageId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 3;</code>
       * @return The token.
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 3;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 3;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 3;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AdminDeleteImageArgs)
    }

    // @@protoc_insertion_point(class_scope:AdminDeleteImageArgs)
    private static final fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs();
    }

    public static fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AdminDeleteImageArgs>
        PARSER = new com.google.protobuf.AbstractParser<AdminDeleteImageArgs>() {
      @java.lang.Override
      public AdminDeleteImageArgs parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AdminDeleteImageArgs(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AdminDeleteImageArgs> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AdminDeleteImageArgs> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public fctreddit.impl.grpc.generated_java.ImageAdminProtoBuf.AdminDeleteImageArgs getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AdminDeleteImageArgs_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AdminDeleteImageArgs_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,src/fctreddit/impl/api/grpc/ImageAdmin" +
      ".proto\032\033google/protobuf/empty.proto\"F\n\024A" +
      "dminDeleteImageArgs\022\016\n\006userId\030\001 \001(\t\022\017\n\007i" +
      "mageId\030\002 \001(\t\022\r\n\005token\030\003 \001(\t2P\n\nImageAdmi" +
      "n\022B\n\017deleteUserImage\022\025.AdminDeleteImageA" +
      "rgs\032\026.google.protobuf.Empty\"\000B8\n\"fctredd" +
      "it.impl.grpc.generated_javaB\022ImageAdminP" +
      "rotoBufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_AdminDeleteImageArgs_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AdminDeleteImageArgs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AdminDeleteImageArgs_descriptor,
        new java.lang.String[] { "UserId", "ImageId", "Token", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
